<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;netstandard2.0</TargetFrameworks>
    <RootNamespace>Irvin.Extensions</RootNamespace>
    <AssemblyName>SystemExtensions</AssemblyName>
    <Version>1.4.0</Version>
    <Product />
    <Authors>Nate Irvin</Authors>
    <Copyright>Copyright © Nathaniel Irvin 2013-2024</Copyright>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Irvin.SystemExtensions</PackageId>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>A .NET Standard library containing enhancements to System libraries.</Description>
    <RepositoryUrl>https://github.com/irvinsoftware/system-extensions</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageVersion>1.5.0</PackageVersion>
    <AssemblyVersion>1.4.0</AssemblyVersion>
    <FileVersion>1.4.0</FileVersion>
    <LangVersion>10</LangVersion>
    <Configurations>Debug;Release;DebugEverything</Configurations>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'DebugEverything' ">
    <DebugSymbols Condition=" '$(DebugSymbols)' == '' ">true</DebugSymbols>
    <Optimize Condition=" '$(Optimize)' == '' ">false</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
